force-app/main/default/objects/Account/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Sales_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Sales_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Invoice</label>
    <referenceTo>Sales_Invoice__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/Sales_Invoice__c.object-meta.xml
<CustomObject>
    <label>Sales Invoice</label>
    <nameField>
        <displayFormat>I{00}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Invoices</relationshipLabel>
    <relationshipName>Sales_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/mailInvoiceHClassTest.cls
@isTest
private class mailInvoiceHClassTest {
    @isTest
    static void setUpData(){
            Account testAccount = new Account(
            Name= 'Test Account',
            AccountNumber='123456'
        );
        insert testAccount;
        
         Contact testContact = new Contact(
            FirstName= 'Test',
            LastName= 'Contact',
            Email= 'pallavi.1923cs1189@kiet.edu',
            AccountId = testAccount.Id
        );
        insert testContact;
        
        testAccount.Contact__c=testContact.Id;
		update testAccount; 
        Id standardbookPrice = Test.getStandardPricebookId();
        
        Opportunity testOpportunity = new Opportunity(
            Name= 'Test Opportunity',
            StageName = 'Closed Won',
            CloseDate = Date.today(),
            Pricebook2Id = standardbookPrice,
            Amount= 10000,
            AccountId = testAccount.Id
        );
        insert testOpportunity;
        
        Product2 testProduct= new Product2(
            Name= 'Test Product',
            IsActive= true
        );
        insert testProduct;
        
        
        
        PricebookEntry testPriceBookEntry = new PricebookEntry(
          IsActive = true,
          Product2Id = testProduct.Id,
          Pricebook2Id = standardbookPrice,
          UnitPrice = 5000
        );
        insert testPriceBookEntry;

        OpportunityLineItem testOpportunityLineItem =new OpportunityLineItem(
            Product2Id= testProduct.Id,
            OpportunityId= testOpportunity.Id,
            Quantity= 2,
            UnitPrice= 5000
        );
        insert testOpportunityLineItem;
        Sales_Invoice__c testCustomInvoice= new Sales_Invoice__c(
            Opportunity__c= testOpportunity.Id,
            Account__c= testAccount.Id,
            Invoice_Date__c= Datetime.now(),
            Due_Date__c = testOpportunity.CloseDate.addDays(30)
        );
        Test.startTest();
        insert testCustomInvoice;
        List<Sales_Invoice__c> newRecordList = new List<Sales_Invoice__c>{testCustomInvoice};
            Test.stopTest();
        System.assertEquals(1,Limits.getEmailInvocations());
        
    }
}